using System;

public class Program
{
	public static void Main(string[] args)
	{
		string[] letters = new string[]
		{
			"AA",
			"AB",
			"AC",
			"AD",
			"AE",
			"AF",
			"AG",
			"AH",
			"AI",
			"AJ",
			"AK",
			"AL",
			"AM",
			"AN",
			"AO",
			"AP",
			"AQ",
			"AR",
			"AS",
			"AT",
			"AU",
			"AV",
			"AW",
			"AX",
			"BA",
			"BB",
			"BC",
			"BD",
			"BE",
			"BF",
			"BG",
			"BH",
			"BI",
			"BJ",
			"BK",
			"BL",
			"BM",
			"BN",
			"BO",
			"BP",
			"BQ",
			"BR",
			"BS",
			"BT",
			"BU",
			"BV",
			"BW",
			"BX",
			"CA",
			"CB",
			"CC",
			"CD",
			"CE",
			"CF",
			"CG",
			"CH",
			"CI",
			"CJ",
			"CK",
			"CL",
			"CM",
			"CN",
			"CO",
			"CP",
			"CQ",
			"CR",
			"CS",
			"CT",
			"CU",
			"CV",
			"CW",
			"CX",
			"DA",
			"DB",
			"DC",
			"DD",
			"DE",
			"DF",
			"DG",
			"DH",
			"DI",
			"DJ",
			"DK",
			"DL",
			"DM",
			"DN",
			"DO",
			"DP",
			"DQ",
			"DR",
			"DS",
			"DT",
			"DU",
			"DV",
			"DW",
			"DX",
			"EA",
			"EB",
			"EC",
			"ED",
			"EE",
			"EF",
			"EG",
			"EH",
			"EI",
			"EJ",
			"EK",
			"EL",
			"EM",
			"EN",
			"EO",
			"EP",
			"EQ",
			"ER",
			"ES",
			"ET",
			"EU",
			"EV",
			"EW",
			"EX",
			"FA",
			"FB",
			"FC",
			"FD",
			"FE",
			"FF",
			"FG",
			"FH",
			"FI",
			"FJ",
			"FK",
			"FL",
			"FM",
			"FN",
			"FO",
			"FP",
			"FQ",
			"FR",
			"FS",
			"FT",
			"FU",
			"FV",
			"FW",
			"FX",
			"GA",
			"GB",
			"GC",
			"GD",
			"GE",
			"GF",
			"GG",
			"GH",
			"GI",
			"GJ",
			"GK",
			"GL",
			"GM",
			"GN",
			"GO",
			"GP",
			"GQ",
			"GR",
			"GS",
			"GT",
			"GU",
			"GV",
			"GW",
			"GX",
			"HA",
			"HB",
			"HC",
			"HD",
			"HE",
			"HF",
			"HG",
			"HH",
			"HI",
			"HJ",
			"HK",
			"HL",
			"HM",
			"HN",
			"HO",
			"HP",
			"HQ",
			"HR",
			"HS",
			"HT",
			"HU",
			"HV",
			"HW",
			"HX",
			"IA",
			"IB",
			"IC",
			"ID",
			"IE",
			"IF",
			"IG",
			"IH",
			"II",
			"IJ",
			"IK",
			"IL",
			"IM",
			"IN",
			"IO",
			"IP",
			"IQ",
			"IR",
			"IS",
			"IT",
			"IU",
			"IV",
			"IW",
			"IX",
			"JA",
			"JB",
			"JC",
			"JD",
			"JE",
			"JF",
			"JG",
			"JH",
			"JI",
			"JJ",
			"JK",
			"JL",
			"JM",
			"JN",
			"JO",
			"JP",
			"JQ",
			"JR",
			"JS",
			"JT",
			"JU",
			"JV",
			"JW",
			"JX",
			"KA",
			"KB",
			"KC",
			"KD",
			"KE",
			"KF",
			"KG",
			"KH",
			"KI",
			"KJ",
			"KK",
			"KL",
			"KM",
			"KN",
			"KO",
			"KP",
			"KQ",
			"KR",
			"KS",
			"KT",
			"KU",
			"KV",
			"KW",
			"KX",
			"LA",
			"LB",
			"LC",
			"LD",
			"LE",
			"LF",
			"LG",
			"LH",
			"LI",
			"LJ",
			"LK",
			"LL",
			"LM",
			"LN",
			"LO",
			"LP",
			"LQ",
			"LR",
			"LS",
			"LT",
			"LU",
			"LV",
			"LW",
			"LX",
			"MA",
			"MB",
			"MC",
			"MD",
			"ME",
			"MF",
			"MG",
			"MH",
			"MI",
			"MJ",
			"MK",
			"ML",
			"MM",
			"MN",
			"MO",
			"MP",
			"MQ",
			"MR",
			"MS",
			"MT",
			"MU",
			"MV",
			"MW",
			"MX",
			"NA",
			"NB",
			"NC",
			"ND",
			"NE",
			"NF",
			"NG",
			"NH",
			"NI",
			"NJ",
			"NK",
			"NL",
			"NM",
			"NN",
			"NO",
			"NP",
			"NQ",
			"NR",
			"NS",
			"NT",
			"NU",
			"NV",
			"NW",
			"NX",
			"OA",
			"OB",
			"OC",
			"OD",
			"OE",
			"OF",
			"OG",
			"OH",
			"OI",
			"OJ",
			"OK",
			"OL",
			"OM",
			"ON",
			"OO",
			"OP",
			"OQ",
			"OR",
			"OS",
			"OT",
			"OU",
			"OV",
			"OW",
			"OX",
			"PA",
			"PB",
			"PC",
			"PD",
			"PE",
			"PF",
			"PG",
			"PH",
			"PI",
			"PJ",
			"PK",
			"PL",
			"PM",
			"PN",
			"PO",
			"PP",
			"PQ",
			"PR",
			"PS",
			"PT",
			"PU",
			"PV",
			"PW",
			"PX",
			"QA",
			"QB",
			"QC",
			"QD",
			"QE",
			"QF",
			"QG",
			"QH",
			"QI",
			"QJ",
			"QK",
			"QL",
			"QM",
			"QN",
			"QO",
			"QP",
			"QQ",
			"QR",
			"QS",
			"QT",
			"QU",
			"QV",
			"QW",
			"QX",
			"RA",
			"RB",
			"RC",
			"RD",
			"RE",
			"RF",
			"RG",
			"RH",
			"RI",
			"RJ",
			"RK",
			"RL",
			"RM",
			"RN",
			"RO",
			"RP",
			"RQ",
			"RR",
			"RS",
			"RT",
			"RU",
			"RV",
			"RW",
			"RX",
			"SA",
			"SB",
			"SC",
			"SD",
			"SE",
			"SF",
			"SG",
			"SH",
			"SI",
			"SJ",
			"SK",
			"SL",
			"SM",
			"SN",
			"SO",
			"SP",
			"SQ",
			"SR",
			"SS",
			"ST",
			"SU",
			"SV",
			"SW",
			"SX",
			"TA",
			"TB",
			"TC",
			"TD",
			"TE",
			"TF",
			"TG",
			"TH",
			"TI",
			"TJ",
			"TK",
			"TL",
			"TM",
			"TN",
			"TO",
			"TP",
			"TQ",
			"TR",
			"TS",
			"TT",
			"TU",
			"TV",
			"TW",
			"TX",
			"UA",
			"UB",
			"UC",
			"UD",
			"UE",
			"UF",
			"UG",
			"UH",
			"UI",
			"UJ",
			"UK",
			"UL",
			"UM",
			"UN",
			"UO",
			"UP",
			"UQ",
			"UR",
			"US",
			"UT",
			"UU",
			"UV",
			"UW",
			"UX",
			"VA",
			"VB",
			"VC",
			"VD",
			"VE",
			"VF",
			"VG",
			"VH",
			"VI",
			"VJ",
			"VK",
			"VL",
			"VM",
			"VN",
			"VO",
			"VP",
			"VQ",
			"VR",
			"VS",
			"VT",
			"VU",
			"VV",
			"VW",
			"VX",
			"WA",
			"WB",
			"WC",
			"WD",
			"WE",
			"WF",
			"WG",
			"WH",
			"WI",
			"WJ",
			"WK",
			"WL",
			"WM",
			"WN",
			"WO",
			"WP",
			"WQ",
			"WR",
			"WS",
			"WT",
			"WU",
			"WV",
			"WW",
			"WX",
			"XA",
			"XB",
			"XC",
			"XD",
			"XE",
			"XF",
			"XG",
			"XH",
			"XI",
			"XJ",
			"XK",
			"XL",
			"XM",
			"XN",
			"XO",
			"XP",
			"XQ",
			"XR",
			"XS",
			"XT",
			"XU",
			"XV",
			"XW",
			"XX"
		};
		string[] words = new string[]
		{
			"AA Batteries",
			"Abs",
			"Air conditioning",
			"Advertisement",
			"Aeroplane",
			"As Fuck",
			"Age",
			"Adolf Hitler",
			"artificial intelligence",
			"Apple Juice",
			"AK 47",
			"Aluminium",
			"Am (time)",
			"annoying",
			"AYO",
			"Apple",
			"Aqua",
			"AR 16",
			"Ass",
			"At (a meeting centre)",
			"OUCH (pain)",
			"cable of some sort",
			"Awww",
			"Axe",
			"Bagel",
			"BB gun",
			"Bacon",
			"Bed",
			"Bee",
			"Best Friend",
			"Bag",
			"Bee Hive",
			"Bi sexual",
			"Blow Job",
			"Burger King",
			"Black",
			"Bum",
			"Bone",
			"Boo!",
			"Beep",
			"BBQ",
			"Bar",
			"Bull shit",
			"Bat",
			"Bus",
			"Believe",
			"Bow",
			"Box",
			"Canada",
			"Cab (taxi)",
			"Coconut",
			"Code",
			"Cement",
			"Coffee",
			"CGI",
			"Cheese",
			"City",
			"CJ (San Andreas)",
			"Cake",
			"Clown",
			"Cum",
			"Can",
			"Coke",
			"Cop",
			"Sequel",
			"Cross",
			"Counter Strike",
			"Counter Terrorist",
			"Cucumber",
			"CCTV (camera security)",
			"Cock Warning",
			"Cox",
			"Daddy",
			"Doorbell",
			"marvel DC",
			"double dicks",
			"Devil",
			"DNF",
			"Dog",
			"Dough",
			"DIY",
			"DJ",
			"Donkey Kong",
			"Dick long",
			"Direct messaging",
			"The end",
			"Dope",
			"Police Department",
			"Duck",
			"Drugs",
			"Nintendo DS",
			"Double Time (osu! stuff)(Gamer cringe)",
			"Dumb",
			"DVD",
			"Darth Waiter",
			"Dicks",
			"EA sports",
			"eBook",
			"Eco",
			"ED SHEERAN",
			"Rush E",
			"Elf",
			"Egg",
			"Eh sight",
			"Eifel tower",
			"Edge",
			"Equator",
			"Electric",
			"Eminem",
			"English",
			"Leo",
			"Episode",
			"Equality",
			"Error",
			"Espanol",
			"Eat",
			"Europe",
			"Evil",
			"EEEW! (yucky)",
			"Explosion",
			"Fart",
			"Football",
			"FC Barcelona",
			"Forward",
			"Federation",
			"F in the chat",
			"Fog",
			"Fire hydrant",
			"Fish",
			"Fiji water",
			"Fork",
			"Flashlight",
			"Film",
			"Fan",
			"Ford",
			"Fps",
			"Frequency",
			"French",
			"Fast",
			"Feet",
			"Fuck",
			"Favourite",
			"Forward",
			"Fax",
			"Game",
			"Great Britain",
			"Greece",
			"God",
			"German",
			"Girlfriend",
			"Good game",
			"Ghost",
			"Gin",
			"Good job",
			"Gate keeper",
			"Good luck",
			"Good morning",
			"Good night",
			"Go",
			"Gap",
			"Guacamole",
			"Green",
			"Nintendo GS",
			"Nissan GTR",
			"Gustav",
			"Grave",
			"Glow",
			"Opera GX",
			"HAHA",
			"Hobby",
			"Hand cam",
			"HD quality",
			"He",
			"Hot fire",
			"Hang",
			"Hedgehog",
			"Hi",
			"Hijack",
			"Hike",
			"Hill",
			"HMMMMMMM",
			"Hannah",
			"Hoe",
			"Health points",
			"Headquarters",
			"Hour",
			"Headshot",
			"Hit",
			"Hugo",
			"HIV",
			"Homework",
			"Hacks",
			"Ian",
			"Ice breakers",
			"I see",
			"ID",
			"Internet Explorer",
			"if",
			"Instagram",
			"Incredible Hulk",
			"2",
			"Indiana Jones",
			"I know",
			"ill",
			"Iron Man",
			"Inch",
			".io game",
			"IP address",
			"IQ",
			"Iron",
			"ISIS",
			"IT tech",
			"I owe you",
			"4",
			"I win",
			"9",
			"Jam",
			"Job",
			"Jackie Chan",
			"Jedi",
			"Jeep",
			"Jet fighter",
			"Juggernaut",
			"Hijab",
			"Jim",
			"Yoyo",
			"Joke",
			"Jail",
			"Jamming",
			"June",
			"Jo mama",
			"JPerm",
			"Jack",
			"Junior",
			"JavaScript",
			"Yeet",
			"June",
			"Juvenile prison",
			"Jaw",
			"Jinx",
			"Kangaroo",
			"Kebab",
			"Ketchup",
			"Kill death ratio",
			"Ketamine",
			"Coffee",
			"King",
			"DJ Khaled",
			"Kiss",
			"Kirgizstan",
			"Ok",
			"kill",
			"Kilometre",
			"Knot",
			"K.O.",
			"Creep",
			"King&queen",
			"Karate",
			"Kys",
			"Katana",
			"Kukavica",
			"Kevlar",
			"Kiwi",
			"Kicks",
			"Los Andreas",
			"Leo Barta",
			"Low cost",
			"LED",
			"Leap",
			"Leaf",
			"Log",
			"Low health",
			"Little",
			"Lebron James",
			"Lake",
			"Lol",
			"Lame",
			"Line",
			"Low",
			"Low percentage",
			"Low quality",
			"Left right",
			"Los Santos",
			"Loot",
			"Lucid",
			"Love",
			"Low",
			"Latex",
			"Mafia",
			"Mobb Deep",
			"Minecraft",
			"Mods",
			"Me",
			"Mf",
			"Magnum",
			"Meh",
			"Mile",
			"M. J. Demarco",
			"My keyboard (MK21)",
			"Mall",
			"Minimum",
			"Man",
			"Moo",
			"Mini power",
			"My cubes",
			"Mister",
			"Miss",
			"Matt",
			"Mum",
			"micro voltage",
			"Microwave",
			"Maximum",
			"North America",
			"Nose bleeds",
			"New Carolina",
			"Nerd",
			"New",
			"Not Finished",
			"No game",
			"NAH",
			"Niger",
			"Ninja",
			"Knuckles",
			"NHL",
			"No Milk",
			"No Nut November",
			"Noob",
			"No Problem",
			"Nyquil (sleeping pills)",
			"New Rich",
			"Nos (nitro)",
			"Nut",
			"Number",
			"Nivara",
			"News",
			"Nexus",
			"Orangutan",
			"OBI",
			"Octopus",
			"Oder",
			"Omelette",
			"Of course",
			"You’re an OG",
			"OH",
			"Oil",
			"Orange juice",
			"Ok",
			"OLL",
			"Oh my god",
			"Oh no",
			"Short Castling",
			"Operator",
			"Oh quack",
			"Or else…",
			"Osu",
			"Oatmeal",
			"Ouch",
			"Oval",
			"Owl",
			"Oxygen",
			"Paw",
			"Personal best",
			"Computer",
			"Pad",
			"Pet",
			"Profile",
			"Page",
			"Pedophile",
			"3.1415926",
			"Pyjamas",
			"Peak",
			"Poland",
			"Palm",
			"Phone",
			"PO (Kung Fu panda)",
			"PP",
			"Pop quiz",
			"Personal record",
			"PlayStation",
			"Put",
			"Push up",
			"Pervert",
			"Power",
			"Pixel",
			"Quality",
			"Cube",
			"Quick",
			"Quandaile Dingle",
			"Question",
			"Queef",
			"Queens gambit",
			"Quite hard",
			"QIYI",
			"Quick jump",
			"Quack",
			"Book and quill",
			"Quagmire",
			"Queen",
			"Quote",
			"Cockpit",
			"Queue",
			"QR code",
			"Quasar",
			"Quit",
			"Cute",
			"Quiver",
			"QWERTY",
			"Quick sand",
			"Ramp",
			"Road block",
			"Race",
			"Ride",
			"Retire",
			"Race formula",
			"Rage",
			"Rhino",
			"Rice",
			"Road jump",
			"Rake",
			"Real",
			"Room",
			"Right now",
			"Rope",
			"RPG",
			"Reading quickly",
			"Rolce Royce",
			"Rest",
			"Retrieve",
			"Rush",
			"Rave",
			"Raw",
			"T-rex",
			"Sand",
			"SuperBet",
			"Score",
			"SD card",
			"Sell",
			"Sound effects",
			"Set seed glitchless",
			"SHH",
			"Self improvement",
			"Sargant",
			"Slovakia",
			"Slow",
			"Smite",
			"Soon",
			"So good",
			"Speed",
			"sequel",
			"Slovak Republic",
			"SS 100%",
			"Student",
			"SUV",
			"Sven",
			"Swollen",
			"Saxophone",
			"Tatry",
			"Tube",
			"Taco",
			"Tablet driver",
			"Teddy bear",
			"The fuck?",
			"Together",
			"Teeth",
			"Time",
			"Toyota",
			"Take",
			"TLauncher",
			"Team",
			"Teen",
			"Tortilla",
			"Torpedo",
			"Tequila",
			"Tren (YEAA BUDDY LIGHT WEIGHT)",
			"Test",
			"Tattoo",
			"Turist",
			"Tuvalu",
			"Twilight;",
			"Texas",
			"United Arab Emirates",
			"Ultra Banking",
			"Uncommon",
			"Under",
			"United Emirates",
			"UFF",
			"Ultra gamer",
			"UHH",
			"User Interface UI",
			"Ultra jump",
			"United Kingdom",
			"Unlimited love",
			"UMM",
			"Uno the game",
			"Unofficial",
			"Up",
			"Unique",
			"Unstable rate",
			"‘MERICA",
			"Ultra",
			"U2",
			"UV rays from the sun",
			"UWU",
			"User expirience",
			"Van",
			"Volleyball",
			"Voice chat",
			"Vandalism",
			"Very exhauster",
			"Very firm",
			"Vulgar",
			"Very hungry",
			"Very intelligent",
			"Very jealous",
			"Very kind",
			"Very lave",
			"Very mature",
			"Very normal",
			"Very old",
			"VIP",
			"Very high quality",
			"Virtual reality",
			"Visual studio",
			"Veteran",
			"Vulture",
			"Very well",
			"Volkswagen",
			"Vortex",
			"War",
			"Wardrobe",
			"Toilet",
			"World",
			"We",
			"Wtf",
			"Wig",
			"Wall hack",
			"Wi (Yes in French)",
			"World job",
			"Wake up",
			"Wall",
			"Woman",
			"Wine",
			"Wool",
			"Well player",
			"World queue",
			"World record",
			"World saved",
			"Watt",
			"What About You",
			"Wave",
			"World wide web",
			"winks",
			"Xanax",
			"Xbox",
			"Exceed",
			"XD",
			"Xenon",
			"extra far",
			"expert gamer",
			"Extreme hills",
			"11",
			"extra jump",
			"extra king",
			"XL size",
			"extra morning",
			"extra nice",
			"XOXO <3",
			"XP",
			"extra queue",
			"extra race",
			"extra sex",
			"extra time",
			"extra U-turn",
			"15",
			"extra windy",
			"xxx"
		};
		for (int j = 0; j != -1; j++)
		{
			string prompt = "Type out the letters devided by a comma ','";
			Console.WriteLine(prompt);
			string input = Console.ReadLine();
			char[] separators = new char[]
			{
				' ',
				','
			};
			string[] sections = input.Split(separators, StringSplitOptions.RemoveEmptyEntries);
			string final = "";
			foreach (var letter in sections)
			{
				for (int i = 0; i != letters.Length; i++)
				{
					if (letter.Trim() == letters[i])
					{
						string temp = final;
						final = temp + ',' + words[i];
						break;
					}
				}
			}

			Console.WriteLine(final.TrimStart(','));
		}
	}


	// Sets up the function to split a string and print the separated values.
	public void SetUp()
	{
		char[] separators = new char[]
		{
			'='
		};
		char quotes = '"';
		string[] letter = new string[23232];
		string[] word = new string[23232];
		string s = "AA = AA Batteries/AB = Abs/AC = Air conditioning/AD = Advertisement/AE = Aeroplane/AF = As Fuck/AG = Age/AH = Adolf Hitler/AI = artificial intelligence/AJ = Apple Juice/AK = AK 47/AL = Aluminium/AM = Am (time)/AN = annoying/AO = AYO/AP = Apple/AQ = Aqua/AR = AR 16/AS = Ass/AT = At (a meeting centre)/AU = OUCH (pain)/AV = cable of some sort/AW = Awww/AX = Axe/BA = Bagel/BB = BB gun/BC = Bacon/BD = Bed/BE = Bee/BF = Best Friend/BG = Bag/BH = Bee Hive/BI = Bi sexual/BJ = Blow Job/BK = Burger King/BL = Black/BM = Bum/BN = Bone/BO = Boo!/BP = Beep/BQ = BBQ/BR = Bar/BS = Bull shit/BT = Bat/BU = Bus/BV = Believe/BW = Bow/BX = Box/CA = Canada/CB = Cab (taxi)/CC = Coconut/CD = Code/CE = Cement/CF = Coffee/CG = CGI/CH = Cheese/CI = City/CJ = CJ (San Andreas)/CK = Cake/CL = Clown/CM = Cum/CN = Can/CO = Coke/CP = Cop/CQ = Sequel/CR = Cross/CS =  Counter Strike/CT = Counter Terrorist/CU = Cucumber/CV = CCTV (camera security)/CW = Cock Warning/CX = Cox/DA = Daddy/DB = Doorbell/DC = marvel DC/DD = double dicks/DE = Devil/DF = DNF/DG = Dog/DH = Dough/DI = DIY/DJ = DJ/DK = Donkey Kong/DL = Dick long/DM = Direct messaging/DN = The end/DO = Dope/DP = Police Department/DQ = Duck/DR = Drugs/DS = Nintendo DS/DT = Double Time (osu! stuff)(Gamer cringe)/DU =Dumb/DV = DVD/DW = Darth Waiter/DX = Dicks/EA = EA sports/EB = eBook/EC = Eco/ED = ED SHEERAIN/EE = Rush E/EF = Elf/EG = Egg/EH = Eh sight/EI = Eifel tower/EJ = Edge/EK = Equator/EL = Electric/EM = Eminem/EN = English/EO = Leo/EP = Episode/EQ = Equality/ER = Error/ES = Espanol/ET = Eat/EU = Europe/EV = Evil/EW = EEEW! (yucky)/EX = Explosion/FA = Fart/FB = Football/FC = FC Barcelona/FD = Forward/FE = Federation/FF = F in the chat/FG = Fog/FH = Fire hydrant/FI = Fish/FJ = Fiji water/FK = Fork/FL = Flashlight/FM = Film/FN = Fan/FO = Ford/FP = Fps/FQ = Frequency/FR = French/FS = Fast/FT = Feet/FU = Fuck/FV = Favourite/FW = Forward/FX = Fax/GA = Game/GB = Great Britain/GC = Greece/GD = God/GE = German/GF = Girlfriend/GG = Good game/GH = Ghost/GI = Gin/GJ = Good job/GK = Gate keeper/GL = Good luck/GM = Good morning/GN = Good night/GO = Go/GP = Gap/GQ = Guacamole/GR = Green/GS = Nintendo GS/GT = Nissan GTR/GU = Gustav/GV = Grave/GW = Glow/GX = Opera GX/HA = HAHA/HB = Hobby/HC = Hand cam/HD = HD quality/HE = He/HF = Hot fire/HG = Hang/HH = Hedgehog/HI = Hi/HJ = Hijack/HK = Hike/HL = Hill/HM = HMMMMMMM/HN = Hannah/HO = Hoe/HP = Health points/HQ =  Headquarters/HR = Hour/HS = Headshot/HT = Hit/HU = Hugo/HV =  HIV/HW = Homework/HX = Hacks/IA = Ian/IB = Ice breakers/IC = I see/ID = ID/IE = Internet Explorer/IF =  if/IG = Instagram/IH = Incredible Hulk/II =2/IJ = Indiana Jones/IK = I know/IL = ill/IM = Iron Man/IN = Inch/IO = .io game/IP = IP address/IQ = IQ/IR = Iron/IS = ISIS/IT = IT tech/IU = I owe you/IV = 4/IW = I win/IX = 9/JA = Jam/JB = Job/JC = Jackie Chan/JD = Jedi/JE = Jeep/JF = Jet fighter/JG = Juggernaut/JH = Hijab/JI = Jim/JJ = Yoyo/JK = Joke/JL = Jail/JM = Jamming/JN = June/JO = Jo mama/JP = JPerm/JQ = Jack/JR = Junior/JS = JavaScript/JT = Yeet/JU = June/JV = Juvenile prison/JW = Jaw/JX = Jinx/KA = Kangaroo/KB = Kebab/KC = Ketchup/KD = Kill death ratio/KE = Ketamine/KF = Coffee/KG = King/KH = DJ Khaled/KI = Kiss/KJ = Kirgizstan/KK = Ok/KL = kill/KM = Kilometre/KN = Knot/KO = K.O./KP = Creep/KQ = King&queen/KR = Karate/KS = Kys/KT = Katana/KU = Kukavica/KV = Kevlar/KW = Kiwi/KX = Kicks/LA = Los Andreas/LB = Leo Barta/LC = Low cost/LD = LED/LE = Leap/LF = Leaf/LG = Log/LH = Low health/LI = Little/LJ = Lebron James/LK = Lake/LL = Lol/LM = Lame/LN = Line/LO = Low/LP = Low percentage/LQ = Low quality/LR = Left right/LS = Los Santos/LT = Loot/LU = Lucid/LV = Love/LW = Low/LX = Latex/MA = Mafia/MB = Mobb Deep/MC = Minecraft/MD = Mods/ME = Me/MF = Mf/MG = Magnum/MH = Meh/MI = Mile/MJ = M. J. Demarco/MK = My keyboard (MK21)/ML = Mall/MM = Minimum/MN = Man/MO = Moo/MP = Mini power/MQ = My cubes/MR = Mister/MS = Miss/MT = Matt/MU = Mum/MV = micro voltage/MW = Microwave/MX = Maximum/NA = North America/NB = Nose bleeds/NC = New Carolina/ND = Nerd/NE = New/NF = Not Finished/NG = No game/NH = NAH/NI = Niger/NJ = Ninja/NK = Knuckles/NL = NHL/NM = No Milk/NN = No Nut November/NO = Noob/NP = No Problem/NQ = Nyquil (sleeping pills)/NR = New Rich/NS = Nos (nitro)/NT = Nut/NU = Number/NV = Nivara/NW = News/NX = Nexus/OA = Orangutan/OB = OBI/OC = Octopus/OD = Oder/OE = Omelette/OF = Of course/OG = You’re an OG/OH = OH/OI = Oil/OJ = Orange juice/OK = Ok/OL = OLL/OM = Oh my god/ON = Oh no/OO = Short Castling/OP = Operator/OQ = Oh quack/OR = Or else…/OS = Osu/OT = Oatmeal/OU = Ouch/OV = Oval/OW = Owl/OX = Oxygen/PA = Paw/PB = Personal best/PC = Computer/PD = Pad/PE = Pet/PF = Profile/PG = Page/PH = Pedophile/PI = 3.1415926/PJ = Pyjamas/PK = Peak/PL = Poland/PM = Palm/PN = Phone/PO = PO (Kung Fu panda)/PP = PP/PQ = Pop quiz/PR = Personal record/PS = PlayStation/PT = Put/PU = Push up/PV = Pervert/PW = Power/PX = Pixel/QA = Quality/QB = Cube/QC = Quick/QD = Quandaile Dingle/QE = Question/QF = Queef/QG = Queens gambit/QH = Quite hard/QI = QIYI/QJ = Quick jump/QK = Quack/QL = Book and quill/QM = Quagmire/QN = Queen/QO = Quote/QP = Cockpit/QQ = Queue/QR = QR code/QS = Quasar/QT = Quit/QU = Cute/QV = Quiver/QW = QWERTY/QX = Quick sand/RA = Ramp/RB = Road block/RC = Race/RD = Ride/RE = Retire/RF = Race formula/RG = Rage/RH = Rhino/RI = Rice/RJ = Road jump/RK = Rake/RL = Real/RM = Room/RN = Right now/RO = Rope/RP = RPG/RQ = Reading quickly/RR = Rolce Royce/RS = Rest/RT = Retrieve/RU = Rush/RV = Rave/RW = Raw/RX = T-rex/SA = Sand/SB = SuperBet/SC = Score/SD = SD card/SE = Sell/SF = Sound effects/SG = Set seed glitchless/SH = SHH/SI = Self improvement/SJ = Sargant/SK = Slovakia/SL = Slow/SM = Smite/SN = Soon/SO = So good/SP = Speed/SQ = sequel/SR = Slovak Republic/SS = SS 100%/ST = Student/SU = SUV/SV = Sven/SW = Swollen/SX = Saxophone/TA = Tatry/TB = Tube/TC = Taco/TD = Tablet driver/TE = Teddy bear/TF = The fuck?/TG = Together/TH = Teeth/TI = Time/TJ = Toyota/TK = Take/TL = TLauncher/TM = Team/TN = Teen/TO = Tortilla/TP = Torpedo/TQ = Tequila/TR = Tren (YEAA BUDDY LIGHT WEIGHT)/TS = Test/TT = Tattoo/TU = Turist/TV = Tuvalu/TW = Twilight;/TX = Texas/UA = United Arab Emirates/UB = Ultra Banking/UC = Uncommon/UD = Under/UE = United Emirates/UF = UFF/UG = Ultra gamer/UH = UHH/UI = User Interface UI/UJ = Ultra jump/UK = United Kingdom/UL = Unlimited love/UM = UMM/UN = Uno the game/UO = Unofficial/UP = Up/UQ = Unique/UR = Unstable rate/US = ‘MERICA/UT = Ultra/UU = U2/UV = UV rays from the sun/UW = UWU/UX = User expirience/VA = Van/VB = Volleyball/VC = Voice chat/VD = Vandalism/VE = Very exhauster/VF = Very firm/VG = Vulgar/VH = Very hungry/VI = Very intelligent/VJ = Very jealous/VK = Very kind/VL = Very lave/VM = Very mature/VN = Very normal/VO = Very old/VP = VIP/VQ = Very high quality/VR = Virtual reality/VS = Visual studio/VT = Veteran/VU = Vulture/VV = Very well/VW = Volkswagen/VX = Vortex/WA = War/WB = Wardrobe/WC = Toilet/WD = World/WE = We/WF = Wtf/WG = Wig/WH = Wall hack/WI = Wi (Yes in French)/WJ = World job/WK = Wake up/WL = Wall/WM = Woman/WN = Wine/WO = Wool/WP = Well player/WQ = World queue/WR = World record/WS = World saved/WT = Watt/WU = What About You/WV = Wave/WW = World wide web/WX = winks/XA = Xanax/XB = Xbox/XC = Exceed/XD = XD/XE = Xenon/XF = extra far/XG = expert gamer/XH = Extreme hills/XI = 11/XJ = extra jump/XK = extra king/XL = XL size/XM = extra morning/XN = extra nice/XO = XOXO <3/XP = XP/XQ = extra queue/XR = extra race/XS = extra sex/XT = extra time/XU = extra U-turn/XV = 15/XW = extra windy/XX = xxx";
		string[] lines = s.Split('/');
		int i = 0;
		foreach (var line in lines)
		{
			string[] subs = line.Split(separators, StringSplitOptions.RemoveEmptyEntries);
			letter[i] = subs[0];
			word[i] = subs[1];
			Console.WriteLine(quotes + word[i].Trim() + quotes + ',');
			i++;
		}
	}
}